ripcd: make more reliable

diff --git a/ripcd b/ripcd
--- a/ripcd
+++ b/ripcd
@@ -71,6 +71,17 @@ done
 shift $((OPTIND - 1))
 
 #
+# Step 0.  Ensure commands that we require are available.
+#
+for tool in cd-discid cddb-tool cdparanoia diskutil sips; do
+	command -v ${tool} >/dev/null
+	if [ $? -ne 0 ]; then
+		echo "ERROR: ${tool} is required but could not be found" >&2
+		exit 1
+	fi
+done
+
+#
 # Step 1.  If a discid wasn't supplied, find it and save the discinfo.
 #
 if [ -n "${DISCID}" ]; then
@@ -82,6 +93,10 @@ else
 		exit 1
 	fi
 	DISCID=$(cd-discid /dev/r${CDDEV} | awk '{print $1}')
+	if [ -z "${DISCID}" ]; then
+		echo "ERROR: Could not determine discid." >&2
+		exit 1
+	fi
 	CDDIR="${OUTDIR}/${DISCID}"
 	mkdir -p ${CDDIR}
 	cd-discid /dev/r${CDDEV} >${CDDIR}/discinfo
